name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the artifact to download
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output information
        run: echo "Deploying to ..."