name: Reusable Deploy
on: [ workflow_call, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: echo "Deploying to ${{ github.event.inputs.environment }}"